wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.36
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
batch_size:
  desc: null
  value: 4
ep:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 2.0e-05
max_question_len:
  desc: null
  value: 64
max_seq_len:
  desc: null
  value: 384
